### ISSUE TITLE
Some Errors. Help Needed

### ISSUE THREAD

**Issue by EXXodos911** [TheCyb3rAlpha/BobTheSmuggler#1]
Traceback (most recent call last):
  File "C:\Users\USER\Tools\BobTheSmuggler\BobTheSmuggler.py", line 43, in <module>
    main()
  File "C:\Users\USER\Tools\BobTheSmuggler\BobTheSmuggler.py", line 9, in main
    DisplayBanner(os.path.abspath(BANNER_PATH))
  File "C:\Users\USER\Tools\BobTheSmuggler\core\utilities\utils.py", line 20, in DisplayBanner
    print(file.read())
          ^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 243: character maps to <undefined>

**Comment by TheCyb3rAlpha** [comment]
Hi @EXXodos911,

I don't have all the information about your setup but this error could be due to the encoding format from ASCII text saved in the banner.txt file. Try changing this line in utils.py:

https://github.com/TheCyb3rAlpha/BobTheSmuggler/blob/14e34b5aeced7ddbd71b623b3bfd5ebffcce228d/core/utilities/utils.py#L19
 
to 

`with open(path, 'r', encoding='utf-8') as file:`
 
 Let me know if this works or not.

**Comment by EXXodos911** [comment]
Ok thanks I'll try in a bit.
