### ISSUE TITLE
cant get it  to work

### ISSUE THREAD

**Issue by allbondy** [TheCyb3rAlpha/BobTheSmuggler#6]
after batling all of those mising dependencies i got stuck here

C:\Users\Adnan3\BobTheSmuggler>python3 BobTheSmuggler.py -h
Traceback (most recent call last):
  File "C:\Users\Adnan3\BobTheSmuggler\BobTheSmuggler.py", line 43, in <module>
    main()
  File "C:\Users\Adnan3\BobTheSmuggler\BobTheSmuggler.py", line 9, in main
    DisplayBanner(os.path.abspath(BANNER_PATH))
  File "C:\Users\Adnan3\BobTheSmuggler\core\utilities\utils.py", line 20, in DisplayBanner
    print(file.read())
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 243: character maps to <undefined>

**Comment by savaere** [comment]
i have same problem

**Comment by allbondy** [comment]
> i have same problem

Open the file and delete the asci banner 
Or opet the resources/config/banner.txt
And delete everything in the file and save

**Comment by TheCyb3rAlpha** [comment]
> > i have same problem
> 
> Open the file and delete the asci banner Or opet the resources/config/banner.txt And delete everything in the file and save

For the time being, please follow this. I'm working on a major update that will also resolve this issue.
